// Re-exports only the MDI icons used across WebView panels.
// Import from here (not directly from @mdi/js) so esbuild tree-shakes the rest.
export {
  mdiAlertCircleOutline,
  mdiCheck,
  mdiClose,
  mdiChartTree,
  mdiChevronDown,
  mdiCodeTags,
  mdiContentCopy,
  mdiCrosshairsGps,
  mdiEarth,
  mdiEye,
  mdiEyeOff,
  mdiImage,
  mdiImageMultiple,
  mdiLayers,
  mdiLoading,
  mdiMap,
  mdiMapMarker,
  mdiMapOutline,
  mdiRuler,
  mdiSatelliteVariant,
  mdiTable,
  mdiTableMultiple,
  mdiTrashCan,
  mdiTune,
  mdiVideoBox,
} from '@mdi/js';
